<a href="https://colab.research.google.com/github/AbduFakir/Python-DataScience/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
kohli_runs = np.array([45,72,33,61,88,54,40,76,92,58])
print(kohli_runs)

[45 72 33 61 88 54 40 76 92 58]


In [ ]:
type(kohli_runs)

numpy.ndarray

In [ ]:
kohli_runs.shape

(10,)

In [ ]:
batters = np.array([[34,45,65],[23,56,68],[34,78,43]])
print(batters)

[[34 45 65]
 [23 56 68]
 [34 78 43]]


In [ ]:
batters.shape

(3, 3)

In [ ]:
batters.ndim

2

In [ ]:
batters.dtype

dtype('int64')

In [ ]:
batters.size

9

In [ ]:
batters.nbytes

72

In [ ]:
kohli_runs[0]

np.int64(45)

In [ ]:
kohli_runs[-3:]

array([76, 92, 58])

In [ ]:
batters[1][2]

np.int64(68)

In [ ]:
runs = np.array([10,20,30,40,50,60])
runs.reshape(3,2)

array([[10, 20],
       [30, 40],
       [50, 60]])

In [ ]:
print(runs)

[10 20 30 40 50 60]


In [ ]:
kohli_runs

array([45, 72, 33, 61, 88, 54, 40, 76, 92, 58])

In [ ]:
kohli_runs + 10

array([ 55,  82,  43,  71,  98,  64,  50,  86, 102,  68])

In [ ]:
kohli_runs * 2

array([ 90, 144,  66, 122, 176, 108,  80, 152, 184, 116])

In [ ]:
np.sum(kohli_runs)

np.int64(619)

In [ ]:
np.mean(kohli_runs)

np.float64(61.9)

In [ ]:
np.max(kohli_runs)

np.int64(92)

In [ ]:
np.min(kohli_runs)

np.int64(33)

In [ ]:
np.median(kohli_runs)

np.float64(59.5)

In [ ]:
np.std(kohli_runs)

np.float64(18.886238376129853)

In [ ]:
kohli_runs > 50

array([False,  True, False,  True,  True,  True, False,  True,  True,
        True])

In [ ]:
kohli_runs[kohli_runs > 50]

array([72, 61, 88, 54, 76, 92, 58])

In [ ]:
scores = np.array([[180,175,189],[165,200,210],[150,185,170]])
print(scores)

[[180 175 189]
 [165 200 210]
 [150 185 170]]


In [ ]:
np.mean(scores, axis=1)

array([181.33333333, 191.66666667, 168.33333333])

In [ ]:
np.mean(scores, axis=0)

array([165.        , 186.66666667, 189.66666667])